### ISSUE TITLE
cell pattern interpretation for total cross ties

### ISSUE THREAD

**Issue by a-karanth** [SunPower/PVMismatch#120]
I am trying to build a 16-cell module with a total cross tie connection in a 4x4 layout, such that there is a bypass diode across two rows. The desired layout is shown in Figure 1. In this definition, each block represents a cell, and 8 cells together form a substring in the module.
![Figure1](https://user-images.githubusercontent.com/60980802/77455197-d66d6800-6df9-11ea-9f44-1beafbdca7b9.jpg)

I have defined my module as:
nrows_per_substrs = [2]*2  # for TCT
ncols = 4
pv_mod_pattern = pvmodule.crosstied_cellpos_pat(nrows_per_substrs=nrows_per_substrs, ncols=ncols, partial = False)

Figure 2 is the cellpos_pat array obtained using the above definition. Based on it, is it correct to assume that the cells are connected as shown in figure 3? 
Additionally, in the explanation in the issue 113 (https://github.com/SunPower/PVMismatch/issues/113), it is mentioned that "crosstie" refers to the node before the indexed cell to the next column of the module. Does that mean that in my particular case, the last column of the first substring is in parallel with the first column of the second substring?

![Figure2](https://user-images.githubusercontent.com/60980802/77454498-e8024000-6df8-11ea-8283-14b3f9f3d9aa.jpg)
![Figure3](https://user-images.githubusercontent.com/60980802/77455070-af169b00-6df9-11ea-839e-d3dbdd71fe13.jpg)

**Comment by mikofski** [comment]
Yes
