### ISSUE TITLE
create a google group, discourse, or other forum for users to ask questions

### ISSUE THREAD

**Issue by mikofski** [SunPower/PVMismatch#135]
Currently if users have a usage question their only option is to create an issue. This creates a barrier to free exchange of ideas, as new users may feel their questions don't warrant an issue. A google group, discourse, or php forum/bulletin board would alleviate this.

**Comment by kanderso-nrel** [comment]
FYI: pvmismatch has a small but nonzero presence on stackoverflow: https://stackoverflow.com/search?q=pvmismatch

No comment from me on whether that's better or worse than a google group.

**Comment by chetan201** [comment]
that's really great. 
I will add a note regarding that on the landing page and request users to tag pvmismatch.

**Comment by abooda1981** [comment]
A Google users group would be awesome!

**Comment by chetan201** [comment]
@mikofski I started a GitHub discussions for this repo. Do you think it addresses this issue?
