### ISSUE TITLE
update GITHUB_OAUTH_TOKEN in .travis.yml

### ISSUE THREAD

**Issue by mikofski** [SunPower/PVMismatch#63]
This token [`GITHUB_OAUTH_TOKEN`](../blob/master/.travis.yml#L16) is probably no good anymore for uploading Python wheels and source distros to GitHub anymore. You'll have to generate a new one, or ask @cedricleroy to do it and either add it directly to the travis build settings as a secret environment variable, or use their CLI to create a secure encrypted token that you add to `.travis.yml` - read their docs.

See [the build log from travis where it tried to deploy to GitHub](https://travis-ci.org/SunPower/PVMismatch/jobs/337807155#L820-L824):

>Logged in as Mark Mikofski
Deploying to repo: SunPower/PVMismatch
Current tag is: v3.2.1
POST https://api.github.com/repos/SunPower/PVMismatch/releases: 404 - Not Found
See: https://developer.github.com/v3/repos/releases/#create-a-release (Octokit::NotFound)

---

For PyPI, I don't know what the hell is wrong with it. It's possible that because it couldn't deploy to GitHub, and it tries that first, it just quit, and if that had succeeded it would have worked? Regardless, I already deployed it to PyPI this time. And for next time, you should have your own PyPI account, and so you can change the [pypi username and password in travis](../blob/master/.travis.yml#L24-L25).

**Comment by chetan201** [comment]
I think this is now taken care of. Closing..
