### ISSUE TITLE
PR #73 breaks temperature dependance  

### ISSUE THREAD

**Issue by chetan201** [SunPower/PVMismatch#76]
What's expected - (reverting back to pr #68 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/19290930/39733472-ae630026-5227-11e8-9925-a1a413572f36.png">

What's observed in pr #73  -
<img width="303" alt="image" src="https://user-images.githubusercontent.com/19290930/39733511-e9fcb474-5227-11e8-836c-a672423d8a33.png">

**Comment by chetan201** [comment]
@mikofski  
off the top of your head, do you know why this might be happening? 
Shall I revert the master to PR #68 meanwhile?

**Comment by mikofski** [comment]
Another fix idea, would be to just pick a 4th quadrant current, like -10A, and just go up to that value always. I'll try to implement one of these two approaches and put in a new PR asap. Until then, yes, I think you would be better reverting to 4943742f68a1819d258bf930d89c4b05f06b7630 

sorry!
