### ISSUE TITLE
DOC: BUG: contrib docs not rendering correctly

### ISSUE THREAD

**Issue by mikofski** [SunPower/PVMismatch#94]
see [here](https://sunpower.github.io/PVMismatch/api/contrib.html)

**Comment by mikofski** [comment]
also please take a look at [these comments](../pull/93#issuecomment-428687209) and the suggestions I made after you closed #72

**Comment by chetan201** [comment]
@mikofski 
Thanks for bringing this to my attention, I will regenerate the docs and try again. Not sure why this would happen though!

**Comment by chetan201** [comment]
issue persists in 4.1 - needs closer investigation

**Comment by mikofski** [comment]
@chetan201 I think the issue is simple, you need to use git on your computer to add the generated contrib files to the repository after you copy them to the top level docs/ folder, then, commit and push. I'll open a pr now
